language: objective-c
script:
    - xcodebuild test 
      -workspace Anna.xcworkspace 
      -scheme Anna_iOS 
      -sdk iphonesimulator 
      -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1'
before_install:
    - gem install cocoapods
    - pod repo update
