language: objective-c
script:
    - xctool 
      -workspace Anna.xcworkspace 
      -scheme Anna_iOS 
      clean build test 
      CODE_SIGN_IDENTITY="" 
      CODE_SIGNING_REQUIRED=NO
before_install:
    - gem install cocoapods
    - pod repo update
